### ISSUE TITLE
Align menu with logo height-wise

### ISSUE THREAD

**Issue by elkynator** [Firstbloodio/firstblood-www#1]
IMHO looks better since it is aligned on the top with logo. Not really a critical issue though. :)

![screen shot 2016-11-07 at 10 54 30 pm](https://cloud.githubusercontent.com/assets/5439459/20077740/e4ec6698-a53d-11e6-9e3e-b1b59a75e905.png)

**Comment by JasonMcz** [comment]
I like the current way. @anik657 @zackcoburn @miohtama thoughts?
