### ISSUE TITLE
Language dropdown menu

### ISSUE THREAD

**Issue by elkynator** [Firstbloodio/firstblood-www#11]
Add a dropdown menu for languages to save space. 

Here is an example of such menu function wise (forget the design though, just functions are fine)

![screen shot 2016-11-08 at 9 51 11 pm](https://cloud.githubusercontent.com/assets/5439459/20116674/852fc090-a5fd-11e6-8ce0-bf5ed813abb8.png)

**Comment by JasonMcz** [comment]
Need improvement but fixed this issue with latest push.
