### ISSUE TITLE
More about FB: When hovering on button, paint border in the same color as the hover color

### ISSUE THREAD

**Issue by elkynator** [Firstbloodio/firstblood-www#12]
Currently the gray color stays when hovering which doesn look that nice. 

![screen shot 2016-11-08 at 10 26 08 pm](https://cloud.githubusercontent.com/assets/5439459/20117796/5f4c5bd6-a602-11e6-8ed9-8f2dbf1c5ec9.png)

**Comment by JasonMcz** [comment]
Fixed with 07bb5db..77038f0
