### ISSUE TITLE
Press Coverage: Align the height of news and make them the same size

### ISSUE THREAD

**Issue by elkynator** [Firstbloodio/firstblood-www#14]
We want to have the news section of the same size. We also want some space between news horizontally, currently they are too much together (no padding from the news)

![screen shot 2016-11-08 at 10 34 23 pm](https://cloud.githubusercontent.com/assets/5439459/20118129/af17d6da-a603-11e6-9ea6-50cc176eb744.png)

**Comment by JasonMcz** [comment]
Closed with new commits.
