### ISSUE TITLE
Careers page redesign

### ISSUE THREAD

**Issue by elkynator** [Firstbloodio/firstblood-www#15]
I was thinking about how to address the careers page and made a quick proposal to tune it so we can list requirements about each position and expose the benefits of working at our place.
![careers open position](https://cloud.githubusercontent.com/assets/5439459/20122101/7e1b4992-a615-11e6-9699-fde40f959ebf.png)
![careers](https://cloud.githubusercontent.com/assets/5439459/20122100/7e1a9362-a615-11e6-9c82-66112de22d8d.png)

**Comment by JasonMcz** [comment]
Pushed.
