### ISSUE TITLE
Fixes for jobs page

### ISSUE THREAD

**Issue by elkynator** [Firstbloodio/firstblood-www#22]
Product Designer:
Change subtitle to: Users first, everything else second  -> adding s to user

Front-End Engineer:
Presice -> Precise

- Link to Dribbble, Behance, or your portfolio -> Link to Github or Stackoverflow if you have them
- Link to projects
- CV -> CV or LinkedIn
- Tell us what excites you the most about this role in few sentences
- Your favorite website/app and why -> Delete this part

Senior Full-Stack Engineer:
Change title to Senior Full-Stack Engineer.

- You worked with startups/projects before. -> Delete
- Opportunity to lead and build your team (if that is your thing) -> Delete (if that is your thing)
- To work remotely... -> Delete "yes, you can take your time to focus and do the work"

- Link to Github & Linkedin -> Link to Github or Stackoverflow account if you have them
- CV -> CV and LinkedIn with links to projects
- Your favorite website/app and why -> Delete this part

**Comment by JasonMcz** [comment]
@elkynator Could you make edits on google doc so I can just copy paste? Thanks.

**Comment by JasonMcz** [comment]
Fixed.
