### ISSUE TITLE
News & Update: Font size for description too small 

### ISSUE THREAD

**Issue by elkynator** [Firstbloodio/firstblood-www#6]
Font size too small to be used on web. It is not readable. Let's increase the font size to 14px. That is the minimum which is used on web nowadays.

![screen shot 2016-11-08 at 10 16 00 pm](https://cloud.githubusercontent.com/assets/5439459/20117468/0dee7d38-a601-11e6-9588-290fa3c62d77.png)

**Comment by yokosogithub** [comment]
I can fix it

**Comment by JasonMcz** [comment]
@yokosogithub welcome pull request.

**Comment by JasonMcz** [comment]
Merged & Closed.
